/*
 * About.java
 *
 * Created on 11 October 2004, 15:10
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs;

/**
 *
 * @author  smf
 */
public class AboutDialog extends javax.swing.JDialog {

    // private members
    // the program version numbers
    public static final String PROGRAM_NAME = "INTERMAGNET CD Data Viewer";
    public static final int VERSION_NUMBER_MAJOR = 1;
    public static final int VERSION_NUMBER_MINOR = 4;
    
    public static String formatVersionNumber ()
    {
        return Integer.toString (VERSION_NUMBER_MAJOR) + "." +
               Integer.toString (VERSION_NUMBER_MINOR);
    }
    
    
    /** Creates new form About */
    public AboutDialog (java.awt.Frame parent, boolean modal, 
                        java.awt.event.ActionListener listener) 
    {
        super(parent, modal);
        initComponents();
        initComponents2(listener);
    }
    
    /** Creates new form About */
    public AboutDialog (java.awt.Dialog parent, boolean modal, 
                        java.awt.event.ActionListener listener) 
    {
        super(parent, modal);
        initComponents();
        initComponents2(listener);
    }
    
    private void initComponents2 (java.awt.event.ActionListener listener)
    {
        AboutLabel1.setText("<html><p><h2>" + PROGRAM_NAME + " Version " + formatVersionNumber () + "</h2></html>");
        AboutLabel2.setText("<html> <h3>Version " + formatVersionNumber () + "</h3> </html>");

        getRootPane().setDefaultButton (CloseButton);

        BGSButton.setActionCommand("show_external_web_page&http://www.geomag.bgs.ac.uk/");
        BGSButton.addActionListener(listener);
        ImagButton.setActionCommand("show_external_web_page&http://www.intermagnet.org/");
        ImagButton.addActionListener(listener);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AboutLabel1 = new javax.swing.JLabel();
        ImagButton = new javax.swing.JButton();
        AboutLabel = new javax.swing.JLabel();
        AboutLabel2 = new javax.swing.JLabel();
        AboutLabel3 = new javax.swing.JLabel();
        BGSButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();

        AboutLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutLabel1.setText("<html>\n<p>\n<h2>INTERMAGNET CD Data Viewer Version 1.0</h2>\n<p>\n<h3>Copyright British Geological Survey 2004</h3>\n</html>");

        setTitle("About ImagCD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        ImagButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgs/geophys/ImagCD/ImagCDViewer/Icons/LgeImag.gif"))); // NOI18N
        ImagButton.setIconTextGap(0);
        ImagButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(ImagButton, gridBagConstraints);

        AboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutLabel.setText("<html>\n<h2>INTERMAGNET CD Data Viewer</h2>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(AboutLabel, gridBagConstraints);

        AboutLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutLabel2.setText("<html> <h3>Version X.X</h3> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(AboutLabel2, gridBagConstraints);

        AboutLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AboutLabel3.setText("<html> <h4>Copyright &copy British Geological Survey 2004-2010</h4> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(AboutLabel3, gridBagConstraints);

        BGSButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgs/geophys/ImagCD/ImagCDViewer/Icons/LgeBGS.gif"))); // NOI18N
        BGSButton.setIconTextGap(0);
        BGSButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        getContentPane().add(BGSButton, gridBagConstraints);

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(CloseButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        closeDialog (null);
    }//GEN-LAST:event_CloseButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutLabel;
    private javax.swing.JLabel AboutLabel1;
    private javax.swing.JLabel AboutLabel2;
    private javax.swing.JLabel AboutLabel3;
    private javax.swing.JButton BGSButton;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton ImagButton;
    // End of variables declaration//GEN-END:variables
    
}
