/*
 * WelcomeDialog.java
 *
 * Created on 18 April 2005, 10:46
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs;

/**
 *
 * @author  smf
 */
public class WelcomeDialog extends javax.swing.JDialog {
    
    /** Creates new form WelcomeDialog */
    public WelcomeDialog(java.awt.Frame parent)
    {
        super(parent, false);
        
        int x, y;
        java.awt.Dimension screen_dim, dialog_dim;
        
        
        // create the dialog contents
        initComponents();
        progressBar.setString("");
        progressBar.setStringPainted(true);
        
        // set the location in the centre of the screen
        screen_dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        dialog_dim = this.getSize();
        x = (screen_dim.width / 2) - (dialog_dim.width / 2);
        if (x < 0) x = 0;
        y = (screen_dim.height / 2) - (dialog_dim.height / 2);
        if (y < 0) y = 0;
        this.setLocation (x, y);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        panel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        label3 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();

        setTitle("Intermagnet Data Viewer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setLayout(new java.awt.BorderLayout());

        panel1.setBorder(new javax.swing.border.EtchedBorder(java.awt.Color.blue, java.awt.Color.cyan));
        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 36));
        label1.setForeground(new java.awt.Color(0, 102, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Intermagnet Data Viewer");
        label1.setToolTipText("Program Initialising");
        label1.setOpaque(true);
        panel1.add(label1, java.awt.BorderLayout.NORTH);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgs/geophys/ImagCD/ImagCDViewer/Icons/WelcomeScreen.gif")));
        label2.setToolTipText("Program Initialising");
        panel1.add(label2, java.awt.BorderLayout.CENTER);

        panel2.setLayout(new java.awt.BorderLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 102, 255));
        jSeparator1.setOpaque(true);
        panel2.add(jSeparator1, java.awt.BorderLayout.NORTH);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Dialog", 0, 12));
        label3.setText("Program initialising, please wait ...");
        label3.setToolTipText("Program Initialising");
        label3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 2, 1, 2)));
        label3.setOpaque(true);
        panel2.add(label3, java.awt.BorderLayout.WEST);

        panel3.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setBackground(new java.awt.Color(255, 255, 255));
        progressBar.setForeground(new java.awt.Color(255, 0, 51));
        progressBar.setMaximumSize(new java.awt.Dimension(32767, 5));
        progressBar.setMinimumSize(new java.awt.Dimension(10, 5));
        progressBar.setPreferredSize(new java.awt.Dimension(300, 5));
        progressBar.setOpaque(false);
        panel3.add(progressBar);

        panel2.add(panel3, java.awt.BorderLayout.CENTER);

        panel1.add(panel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    /** set the progress of initialisation
     * @param progress 0 to 100 percent */
    public void setProgress (int progress)
    {
        progressBar.setValue (progress);
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

}
