/*
 * ImportStep1.java
 *
 * Created on 27 December 2008, 10:33
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs.Import;

import bgs.geophys.ImagCD.ImagCDViewer.Utils.ImportThread;
import bgs.geophys.ImagCD.ImagCDViewer.Utils.ImportThread.GeomagFile;
import bgs.geophys.library.Swing.SwingUtils;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author  smf
 */
public class ImportStep6 extends javax.swing.JPanel 
{
    
    /** Creates new form ImportStep1 */
    public ImportStep6() 
    {
        initComponents();
        
        // fix the table column widths
        SwingUtils.ResizeTableColumnWidths(FileListTable, 1, 1000, 75, 25);
    }
    
    public void setPercentComplete (int percent) { ProgressBar.setValue(percent); }

    /** add a file to the list of files */
    public void addResult (ImportThread.InstallResult install_result)
    {
        DefaultTableModel model;
        String row [];

        row = new String [2];
        row [0] = install_result.getFilename();
        if (install_result.isError())
            row [1] = "<html> <p color=red>" + install_result.getDetails() + "</html>";
        else
            row [1] = install_result.getDetails();
        model = (DefaultTableModel) FileListTable.getModel();
        model.addRow (row);
    }
    
    /** remove all elements from the table */
    public void removeAllResults ()
    {
        DefaultTableModel model;
        
        model = (DefaultTableModel) FileListTable.getModel();
        while (model.getRowCount() > 0)
            model.removeRow(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        TitleLabel = new javax.swing.JLabel();
        FilePanel = new javax.swing.JPanel();
        FileListScrollPane = new javax.swing.JScrollPane();
        FileListTable = new javax.swing.JTable();
        StatusPanel = new javax.swing.JPanel();
        ProgressLabel = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        InstructionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        TitleLabel.setText("<html><h2>Step 6 of 6: Conversion summary</h2><html>"); // NOI18N
        add(TitleLabel, java.awt.BorderLayout.NORTH);

        FilePanel.setLayout(new java.awt.BorderLayout());

        FileListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File name", "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FileListScrollPane.setViewportView(FileListTable);

        FilePanel.add(FileListScrollPane, java.awt.BorderLayout.CENTER);

        StatusPanel.setLayout(new java.awt.GridBagLayout());

        ProgressLabel.setText("Progress:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        StatusPanel.add(ProgressLabel, gridBagConstraints);

        ProgressBar.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        StatusPanel.add(ProgressBar, gridBagConstraints);

        FilePanel.add(StatusPanel, java.awt.BorderLayout.SOUTH);

        add(FilePanel, java.awt.BorderLayout.CENTER);

        InstructionsLabel.setText("<html> \n<h3>Information</h3>  \n\nFiles are being copied to their final destination. Once the copying is complete, a list of the converted files will be shown.\n</html>"); // NOI18N
        add(InstructionsLabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane FileListScrollPane;
    private javax.swing.JTable FileListTable;
    private javax.swing.JPanel FilePanel;
    private javax.swing.JLabel InstructionsLabel;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel ProgressLabel;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
