/*
 * FileErrorPanel.java
 *
 * Created on 01 February 2009, 18:23
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs.DataViewer;

import bgs.geophys.ImagCD.ImagCDViewer.Utils.DisplayData;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  smf
 */
public class FileErrorPanel extends DataViewerPanel
{
    
    private DefaultTableModel table_model;
    
    /** Creates new form FileErrorPanel */
    public FileErrorPanel() 
    {
        initComponents();
        table_model = (DefaultTableModel) ErrorTable.getModel();
    }
    
    /********************************************************************
     * update - update the display with new data
     *
     * @param obsy_name observatory name
     * @param compare_obsy_name comparison observatory name (may be null)
     * @param year displayed date
     * @param month displayed date
     * @param day displayed date
     * @param data_list - the data to display
     * @param time_period - one of the codes from DataCache
     ********************************************************************/
    public void update (String obsy_name, String compare_obsy_name,
                        int year, int month, int day,
                        DisplayData data_list, int time_period)
    {
      int count;
      String text [];
      
      makeTitle ("File errors for: ", obsy_name, compare_obsy_name, true, year, month, day, time_period);
      TitleLabel.setText ("<html><h2>" + getTitle() + "</html>");

      table_model.setRowCount(0);
      while (table_model.getRowCount() > 0) table_model.removeRow(0);
      text = new String [1];
      for (count=0; count<data_list.getNDataLoadErrors(); count++)
      {
          text [0] = obsy_name + ": " + data_list.getDataLoadError (count);
          table_model.addRow(text);
      }
      for (count=0; count<data_list.getNDiffLoadErrors(); count++)
      {
          text [0] = compare_obsy_name + ": " + data_list.getDiffLoadError (count);
          table_model.addRow(text);
      }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        ErrorScrollPane = new javax.swing.JScrollPane();
        ErrorTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        TitleLabel.setText("<html><h2>File reading errors</h2>");
        add(TitleLabel, java.awt.BorderLayout.NORTH);

        ErrorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "There were errors reading the data:"
            }
        ));
        ErrorScrollPane.setViewportView(ErrorTable);

        add(ErrorScrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ErrorScrollPane;
    private javax.swing.JTable ErrorTable;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
