/*
 * CtryObsyListViewerDialog.java
 *
 * Created on 01 March 2007, 12:49
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs;

import bgs.geophys.ImagCD.ImagCDViewer.GlobalObjects;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  smf
 */
public class CtryObsyListViewerDialog extends javax.swing.JDialog 
{
    
    /** Creates new form CtryObsyListViewerDialog */
    public CtryObsyListViewerDialog(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        initComponents2();
    }
    
    /** Creates new form CtryObsyListViewerDialog */
    public CtryObsyListViewerDialog(java.awt.Dialog parent, boolean modal) 
    {
        super(parent, modal);
        initComponents();
        initComponents2();
    }
    
    private void initComponents2 ()
    {
        
        int count, n_files;
        String highlight_on, highlight_off, active;
        File file;
        DateFormat format;
        DefaultTableModel model;
        String rowData [];
                
        format = SimpleDateFormat.getDateTimeInstance();
        rowData = new String [3];
        
        model = (DefaultTableModel) Table.getModel();
        
        ConfigurationDirectoryText.setText (GlobalObjects.config_dir.getAbsolutePath());

        n_files = GlobalObjects.country_table_versions.getNVersions();
        highlight_on = "<html><p color=\"red\">";
        highlight_off = "</html>";
        active = "Active";
        for (count=n_files -1; count>=0; count--)
        {
            file = GlobalObjects.country_table_versions.getFile(count);
            rowData [0] = highlight_on + file.getName () + highlight_off;
            rowData [1] = highlight_on + format.format (new Date (file.lastModified())) + highlight_off;
            rowData [2] = highlight_on + active + highlight_off;
            model.addRow (rowData);
            highlight_on = highlight_off = active = "";
        }
                  
        n_files = GlobalObjects.observatory_table_versions.getNVersions();
        highlight_on = "<html><p color=\"red\">";
        highlight_off = "</html>";
        active = "Active";
        for (count=n_files -1; count>=0; count--)
        {
            file = GlobalObjects.observatory_table_versions.getFile(count);
            rowData [0] = highlight_on + file.getName () + highlight_off;
            rowData [1] = highlight_on + format.format (new Date (file.lastModified())) + highlight_off;
            rowData [2] = highlight_on + active + highlight_off;
            model.addRow (rowData);
            highlight_on = highlight_off = active = "";
        }
        
        n_files = GlobalObjects.scalar_f_table_versions.getNVersions();
        highlight_on = "<html><p color=\"red\">";
        highlight_off = "</html>";
        active = "Active";
        for (count=n_files -1; count>=0; count--)
        {
            file = GlobalObjects.scalar_f_table_versions.getFile(count);
            rowData [0] = highlight_on + file.getName () + highlight_off;
            rowData [1] = highlight_on + format.format (new Date (file.lastModified())) + highlight_off;
            rowData [2] = highlight_on + active + highlight_off;
            model.addRow (rowData);
            highlight_on = highlight_off = active = "";
        }
        pack ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfigDirectoryPanel = new javax.swing.JPanel();
        ConfigLocationLabel = new javax.swing.JLabel();
        ConfigurationDirectoryText = new javax.swing.JTextField();
        TablePane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        CloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration Tables");

        ConfigLocationLabel.setText("Configuration directory:");
        ConfigDirectoryPanel.add(ConfigLocationLabel);

        ConfigurationDirectoryText.setEditable(false);
        ConfigDirectoryPanel.add(ConfigurationDirectoryText);

        getContentPane().add(ConfigDirectoryPanel, java.awt.BorderLayout.NORTH);

        TablePane.setPreferredSize(new java.awt.Dimension(452, 150));
        TablePane.setRequestFocusEnabled(false);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File", "Modified", "Active"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePane.setViewportView(Table);

        getContentPane().add(TablePane, java.awt.BorderLayout.CENTER);

        CloseButton.setText("Close");
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseButton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_CloseButtonActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JPanel ConfigDirectoryPanel;
    private javax.swing.JLabel ConfigLocationLabel;
    private javax.swing.JTextField ConfigurationDirectoryText;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane TablePane;
    // End of variables declaration//GEN-END:variables
    
}
