/*
 * ImportStep1.java
 *
 * Created on 27 December 2008, 10:33
 */

package bgs.geophys.ImagCD.ImagCDViewer.Dialogs.Import;

/**
 *
 * @author  smf
 */
public class ImportStep1 extends javax.swing.JPanel {
    
    /** Creates new form ImportStep1 */
    public ImportStep1() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        InstructionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        TitleLabel.setText("<html><h2>Step 1 of 6: Introduction</h2><html>"); // NOI18N
        add(TitleLabel, java.awt.BorderLayout.NORTH);

        InstructionsLabel.setText("<html>  This wizard allows you to load data into the INTERMAGNET archive format and directory structure. Data can<br> already be in the INTERMAGNET archive format (to allow exisiting files to be updated), or it can be in the INTERMAGNET<br> minute-mean or IAGA 2002 format. In either case, as much information as possible will be copied into the INTERMAGNET<br> archive files. The INTERMAGNET 'DKA' format for K indices is also supported to allow K index data to be loaded.<br> Options allow hourly and daily means to be calculated. Alternatively these data may be read from IAGA 2002 format<br> files if they are present.<br> <br> Data is selected by choosing a directory. The software will attempt to convert all files found in the selected directory.<br> Files from sub-directories can be optionally included as well.<br> <br> A summary of data converted will be presented with options to change or add header fields in the final CD-ROM binary<br> format files<br> <br> At the end of the process, you can choose which of the current data sources to put the new data into, or you can<br> create a new data source. In either case, the new data will be available to view once the wizard completes.<br>  </html>"); // NOI18N
        add(InstructionsLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InstructionsLabel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
    
}
